language: julia

sudo: true

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

git:
  depth: 99999999

matrix:
  fast_finish: true
  allow_failures:
  - julia: 1.0
  - julia: nightly

script:
  - julia -e 'using Pkg;
              Pkg.activate(".");
              Pkg.build("Render")'
  - make

